### ISSUE TITLE
Wrong file paths - unable to compile tex files

### ISSUE THREAD

**Issue by jernejp21** [flathub/net.xm1math.Texmaker#14]
When using flaptak, file paths seem to be wrong.
`/home/user/Documents/test.tex` file path is converted to `/run/user/1000/doc/<some number>/test.tex`.

Why is this conversion happening? If it's happening I'm unable to compile, because I also cannot specify correct path to pdflatex compiler.

I use Zorin OS 16.2 (Ubuntu 20.04).

**Comment by bbhtt** [comment]
>  /home/user/Documents/test.tex file path is converted to /run/user/1000/doc/<some number>/test.tex.

That will only happen if you're adding files outside of xdg-documents, the one location this flatpak has filesystem access to https://github.com/flathub/net.xm1math.Texmaker/blob/420cd4a129dc9735ecf6cabebc8dfbf72255916c/net.xm1math.Texmaker.yaml#L16

If you open files from another location, the [filechooser portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser) comes into play and mounts the selected file in `/run/user/$UID`, hence the "effective" location of that file from the point of view of the app is in `/run/...`

If you need persistent access to these folders as well, you can do `flatpak override --user --filesystem=<path> net.xm1math.Texmaker`, see man flatpak-run for the syntax of the path.

> If it's happening I'm unable to compile, because I also cannot specify correct path to pdflatex compiler.

Can you give steps of what exactly did you do? I opened a sample tex file in ~/Documents and changed it to PDFLaTex in the tools toolbar and ran run and view. It seems to work fine. I also don't see a `/run` path in the titlebar but the actual path in ~/Documents as it should be.
