### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by DubrulleKevin** [flathub/net.xm1math.Texmaker#2]
Hi,

I have an issue with Texmaker 5.0.4 flatpak version.

When I compile a document with F1 shortcut, PDFLatex seems called, but very often, PDF file is not created. I have to insist 5-10 times before PDF generation.

**Comment by dgcampea** [comment]
Does this happen with the non-flatpak version? (seems to be working fine here)

**Comment by DubrulleKevin** [comment]
Well it seems to be OK now... I can't reproduce it anymore.
