### ISSUE TITLE
Pipeline "latex+dvips+ps2pdf+View PDF" doesn't show PDF

### ISSUE THREAD

**Issue by krono86** [flathub/net.xm1math.Texmaker#3]
Hello!
I installed Texmaker with flatpak on my fresh installed CentOS 8.
I found out that the pipeline "latex+dvips+ps2pdf+View PDF" doesn't create PDF.
It seems that the problem is ps2pdf. When I type:
`/var/lib/flatpak/app/net.xm1math.Texmaker/current/active/files/texlive/bin/ps2pdf test.ps`
I obtain:
`/var/lib/flatpak/app/net.xm1math.Texmaker/current/active/files/texlive/bin/gs: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/lib/flatpak/app/net.xm1math.Texmaker/current/active/files/texlive/bin/gs)`
How this issue could be solved.
Thank you.

Ivan

**Comment by dgcampea** [comment]
Hi @krono86, there has been a change to how Texlive is used. Can you retest?
The Texlive binaries are now under: `/app/texlive/bin`.
Calling `/app/texlive/bin/gs` seems to be working:
```
[📦 net.xm1math.Texmaker ~]$  /app/texlive/bin/gs
GPL Ghostscript 9.53.3 (2020-10-01)
Copyright (C) 2020 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GS>
```

**Comment by krono86** [comment]
I compiled my own version of texmaker to solve all of the problems...

**Comment by dgcampea** [comment]
Closing this issue as it's probably fixed by the recent Texlive changes.
